[package]
name = "cargo_crev_web_admin"
version = "2022.126.1309"
description = "Admin CLI for cargo_crev_web"
authors = ["Luciano Bestia"]
edition = "2021"
license = "MIT"
readme = "README.md"
repository = "https://github.com/lucianobestia/cargo_crev_web_admin/"
categories = ["programming"]
keywords = ["crev"]
publish = false

[dependencies]
log = "0.4"
pretty_env_logger="0.4.0"
unwrap = "1.2.1"
termion = "1.5.6"
lazy_static="1.4.0"
chrono="0.4.11"
num-format="0.4.0"